name: client
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.2

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  hexcolor: ^2.0.0
  page_transition: ^1.1.7+2
  carousel_slider: ^3.0.0
  material_design_icons_flutter: ^4.0.5955
  modal_bottom_sheet: ^1.0.0+1
  flutter_chat_bubble: ^1.0.2
  flutter_switch: ^0.2.2
  graphql_flutter: ^4.0.1
  validators: ^2.0.0
  modal_progress_hud: ^0.1.3
  localstorage: ^3.0.6
  http: ^0.13.0
  image_picker: ^0.7.4
  flutter_bloc: ^7.0.0
  bloc: ^7.0.0
  intl: ^0.17.0
  random_string: ^2.1.0
  quiver: ^3.0.0
  flutter_phoenix: ^1.0.0
  pull_to_refresh: ^1.6.4

dev_dependencies:
  flutter_native_splash: ^0.3.0
  flutter_launcher_icons: "^0.8.0"
  flutter_test:
    sdk: flutter

# Launchher icons
flutter_icons:
  android: true
  ios: true
  image_path: "lib/assets/images/launcher.png"
  adaptive_icon_background: "#ffffff"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - lib/assets/images/
    - lib/assets/icons/

  fonts:
    - family: Regular
      fonts:
        - asset: lib/assets/fonts/AppleSDGothicNeoRegular.ttf

    - family: Medium
      fonts:
        - asset: lib/assets/fonts/AppleSDGothicNeoMedium.ttf

    - family: Bold
      fonts:
        - asset: lib/assets/fonts/AppleSDGothicNeoBold.ttf
